### ISSUE TITLE
Panic when main returns without stopping

### ISSUE THREAD

**Issue by jared-s** [ockam-network/ockam#1219]
The new  [Drop impl for Context](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_node/src/context.rs#L23-L32) causes the top level app worker to panic. This is not triggered when `Context::stop` is called, so did not manifest in most examples.

Repro:

```rust
use ockam::Context;

#[ockam::node]
async fn main(ctx: Context) {
    println!("{:?} will panic:", ctx.primary_address());
}

```

Output:
```rust
Apr 09 13:18:44.474  INFO ockam_node::node: Initializing ockam node
Address { tt: 0, inner: [97, 112, 112] } will panic:
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/j/ockam/ockam/implementations/rust/ockam/ockam_node/src/router.rs:152:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /home/j/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:386:21
   4: ockam_node::router::Router::stop_worker::{{closure}}
             at /home/j/ockam/ockam/implementations/rust/ockam/ockam_node/src/router.rs:152:21

```

**Comment by jared-s** [comment]
If we want to keep this new `Drop` implementation, I suppose we could:

- Have some kind of ctx event loop blocking call? Could be added automatically by the node attribute?
- Handle this main ctx case explicitly in the node attribute without introducing any other new mechanisms?
- Decouple Drop from `stop_worker`?

**Comment by jared-s** [comment]
Could you investigate our options here on your next workday @spacekookie ? Thanks!

**Comment by jared-s** [comment]
Also, it looks like any worker will panic on shutdown if this unrwrap goes south:

```rust
let addrs = self.addr_map.remove(addr).unwrap();
```
