### ISSUE TITLE
Secure channel issues in Elixir

### ISSUE THREAD

**Issue by hairyhum** [ockam-network/ockam#1364]
Currently if I try to create a secure channel like in https://github.com/ockam-network/ockam/blob/develop/implementations/elixir/ockam/ockam/test/ockam/secure_channel_test.exs it fails with a following error:
```
12:16:53.846 module=gen_statem line=2403 pid=<0.285.0> [error] GenStateMachine "_8670b935b55b3768" terminating
** (ArgumentError) argument error
    (ockam_vault_software 0.10.1) Ockam.Vault.Software.aead_aes_gcm_encrypt([1, 1], 41, 0, <<209, 95, 203, 150, 233, 125, 73, 250, 197, 85, 1, 145, 36, 73, 194, 93, 243, 193, 138, 236, 73, 173, 235, 251, 4, 152, 65, 19, 9, 223, 83, 63>>, %{type: 0, value: "_8670b935b55b3768"})
    (ockam 0.1.0) lib/ockam/secure_channel/key_establishment_protocol/xx/protocol.ex:267: Ockam.SecureChannel.KeyEstablishmentProtocol.XX.Protocol.encrypt_and_hash/2
    (ockam 0.1.0) lib/ockam/secure_channel/key_establishment_protocol/xx/protocol.ex:181: Ockam.SecureChannel.KeyEstablishmentProtocol.XX.Protocol.encode_message2/1
    (ockam 0.1.0) lib/ockam/secure_channel/key_establishment_protocol/xx/protocol.ex:141: Ockam.SecureChannel.KeyEstablishmentProtocol.XX.Protocol.encode/2
    (ockam 0.1.0) lib/ockam/secure_channel/key_establishment_protocol/xx/responder.ex:26: Ockam.SecureChannel.KeyEstablishmentProtocol.XX.Responder.handle_message/3
    (ockam 0.1.0) lib/ockam/secure_channel/channel.ex:65: Ockam.SecureChannel.Channel.handle_event/4
    (stdlib 3.14) gen_statem.erl:1168: :gen_statem.loop_state_callback/11
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
State: {{:key_establishment, :responder, :awaiting_message1}, %{ciphertext_address: "_0ff2652be91bb23f", initiating_message: %{onward_route: [], payload: <<116, 131, 138, 91, 38, 7, 109, 134, 207, 97, 22, 94, 123, 166, 138, 125, 222, 51, 124, 15, 73, 249, 63, 130, 73, 122, 73, 21, 237, 79, 70, 121>>, return_route: ["_2c31aa63d6cf49bc"]}, key_establishment_protocol: Ockam.SecureChannel.KeyEstablishmentProtocol.XX, plaintext_address: "_8670b935b55b3768", xx_key_establishment_state: %Ockam.SecureChannel.KeyEstablishmentProtocol.XX.Protocol{ck: 33, e: %{private: 32, public: <<144, 96, 24, 34, 102, 69, 175, 201, 144, 196, 41, 106, 172, 3, 203, 81, 8, 227, 158, 19, 26, 181, 220, 160, 78, 99, 34, 59, 33, 137, 100, 54>>}, h: <<93, 247, 43, 103, 185, 101, 173, 209, 22, 143, 10, 108, 117, 109, 242, 28, 32, 79, 126, 100, 252, 104, 43, 230, 163, 171, 75, 104, 44, 141, 182, 75>>, k: nil, m1_payload: "", m2_payload: %{type: 0, value: "_8670b935b55b3768"}, m3_payload: "", n: nil, prologue: "", re: nil, rs: nil, s: %{private: 1, public: <<86, 168, 33, 44, 234, 234, 160, 41, 175, 135, 180, 102, 146, 121, 49, 18, 29, 114, 223, 207, 24, 108, 157, 112, 179, 82, 20, 17, 31, ...>>}, vault: %Ockam.Vault.Software{id: [1, 1]}}}}
Callback mode: :handle_event_function
Postponed events: []
Last event: {:info, %{onward_route: [], payload: <<116, 131, 138, 91, 38, 7, 109, 134, 207, 97, 22, 94, 123, 166, 138, 125, 222, 51, 124, 15, 73, 249, 63, 130, 73, 122, 73, 21, 237, 79, 70, 121>>, return_route: ["_2c31aa63d6cf49bc"]}}
Queued events: []
State: {{:key_establishment, :responder, :awaiting_message1}, %{ciphertext_address: "_0ff2652be91bb23f", initiating_message: %{onward_route: [], payload: <<116, 131, 138, 91, 38, 7, 109, 134, 207, 97, 22, 94, 123, 166, 138, 125, 222, 51, 124, 15, 73, 249, 63, 130, 73, 122, 73, 21, 237, 79, 70, 121>>, return_route: ["_2c31aa63d6cf49bc"]}, key_establishment_protocol: Ockam.SecureChannel.KeyEstablishmentProtocol.XX, plaintext_address: "_8670b935b55b3768", xx_key_establishment_state: %Ockam.SecureChannel.KeyEstablishmentProtocol.XX.Protocol{ck: 33, e: %{private: 32, public: <<144, 96, 24, 34, 102, 69, 175, 201, 144, 196, 41, 106, 172, 3, 203, 81, 8, 227, 158, 19, 26, 181, 220, 160, 78, 99, 34, 59, 33, 137, 100, 54>>}, h: <<93, 247, 43, 103, 185, 101, 173, 209, 22, 143, 10, 108, 117, 109, 242, 28, 32, 79, 126, 100, 252, 104, 43, 230, 163, 171, 75, 104, 44, 141, 182, 75>>, k: nil, m1_payload: "", m2_payload: %{type: 0, value: "_8670b935b55b3768"}, m3_payload: "", n: nil, prologue: "", re: nil, rs: nil, s: %{private: 1, public: <<86, 168, 33, 44, 234, 234, 160, 41, 175, 135, 180, 102, 146, 121, 49, 18, 29, 114, 223, 207, 24, 108, 157, 112, 179, 82, 20, 17, 31, ...>>}, vault: %Ockam.Vault.Software{id: [1, 1]}}}}
```

It seems like the encode expects the address to be binary (or iolist), while `Serializable.serialize` actually returns a map.
Serializable API needs update to be less confusing, but as for secure channel it's not clear what should be in the m2_payload in this case. Should it be BARE encoded address?

I've tried to use a BARE encoded address there with this:
```
diff --git a/implementations/elixir/ockam/ockam/lib/ockam/secure_channel/key_establishment_protocol/xx.ex b/implementations/elixir/ockam/ockam/lib/ockam/secure_channel/key_establishment_protocol/xx.ex
index 7c99332d..b020b767 100644
--- a/implementations/elixir/ockam/ockam/lib/ockam/secure_channel/key_establishment_protocol/xx.ex
+++ b/implementations/elixir/ockam/ockam/lib/ockam/secure_channel/key_establishment_protocol/xx.ex
@@ -9,7 +9,9 @@ defmodule Ockam.SecureChannel.KeyEstablishmentProtocol.XX do
   def setup(options, data) do
     # TODO:
     options =
-      Keyword.put(options, :message2_payload, Serializable.serialize(data.plaintext_address))
+      Keyword.put(options, :message2_payload,
+        Serializable.serialize(data.plaintext_address) |> :bare.encode(Ockam.Wire.Binary.V2.bare_spec(:address))
+        )
 
     with {:ok, data} <- Protocol.setup(options, data) do
       case Keyword.get(options, :role, :initiator) do
``` 

But now I'm getting an error when trying to send messages through the channel:
```
12:22:05.526 module=gen_statem line=2403 pid=<0.299.0> [error] GenStateMachine "_fac40bcd1403d7a7" terminating
** (FunctionClauseError) no function clause matching in Ockam.SecureChannel.Channel.handle_message/4
    (ockam 0.1.0) lib/ockam/secure_channel/channel.ex:73: Ockam.SecureChannel.Channel.handle_message(:info, %{onward_route: ["_fac40bcd1403d7a7", "echo"], payload: "FOO", return_route: []}, {:encrypted_transport, :ready}, %{ciphertext_address: "_74ca6b91b3a7196f", encrypted_transport: %{decrypt: {17, 0}, encrypt: {18, 0}, h: <<113, 201, 179, 153, 97, 211, 2, 99, 154, 66, 106, 182, 77, 182, 153, 92, 35, 229, 237, 245, 7, 49, 49, 25, 195, 61, 212, 202, 111, 42, 255, 211>>}, key_establishment_protocol: Ockam.SecureChannel.KeyEstablishmentProtocol.XX, peer: %{plaintext_address: <<0, 17, 95, 98, 102, 49, 55, 56, 101, 54, 49, 53, 97, 52, 48, 97, 50, 50, 50>>, public_key: <<191, 154, 122, 123, 162, 162, 54, 253, 197, 240, 235, 251, 80, 45, 118, 218, 170, 169, 187, 89, 209, 189, 77, 28, 191, 199, 67, 200, 107, 239, 8, 77>>}, plaintext_address: "_fac40bcd1403d7a7", route_to_peer: ["_5c6aa3fd960f9b9e"], xx_key_establishment_state: %Ockam.SecureChannel.KeyEstablishmentProtocol.XX.Protocol{ck: 14, e: %{private: 2, public: <<86, 97, 13, 131, 172, 62, 111, 171, 246, 35, 117, 144, 80, 37, 155, 56, 142, 85, 73, 188, 165, 33, 111, 107, 221, 165, 180, 216, 20, 98, 8, 87>>}, h: <<113, 201, 179, 153, 97, 211, 2, 99, 154, 66, 106, 182, 77, 182, 153, 92, 35, 229, 237, 245, 7, 49, 49, 25, 195, 61, 212, 202, 111, 42, 255, 211>>, k: 15, m1_payload: "", m2_payload: <<0, 17, 95, 102, 97, 99, 52, 48, 98, 99, 100, 49, 52, 48, 51, 100, 55, 97, 55>>, m3_payload: "", n: 1, prologue: "", re: <<96, 132, 77, 56, 39, 238, 156, 71, 46, 231, 16, 96, 95, 14, 171, 14, 72, 222, 91, 220, 180, 81, 81, 64, 103, 136, 71, 188, 235, 161, 232, 76>>, rs: <<191, 154, 122, 123, 162, 162, 54, 253, 197, 240, 235, 251, 80, 45, 118, 218, 170, 169, 187, 89, 209, 189, 77, 28, 191, 199, 67, 200, 107, 239, 8, 77>>, s: %{private: 1, public: <<136, 180, 218, 181, 71, 146, 21, 199, 6, 129, 243, 45, 128, 169, 61, 76, 234, 103, 14, 141, 124, 215, 155, 99, 159, 241, 150, 6, 70, ...>>}, vault: %Ockam.Vault.Software{id: [2, 1]}}})
    (ockam 0.1.0) lib/ockam/secure_channel/channel.ex:65: Ockam.SecureChannel.Channel.handle_event/4
    (stdlib 3.14) gen_statem.erl:1168: :gen_statem.loop_state_callback/11
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
State: {{:encrypted_transport, :ready}, %{ciphertext_address: "_74ca6b91b3a7196f", encrypted_transport: %{decrypt: {17, 0}, encrypt: {18, 0}, h: <<113, 201, 179, 153, 97, 211, 2, 99, 154, 66, 106, 182, 77, 182, 153, 92, 35, 229, 237, 245, 7, 49, 49, 25, 195, 61, 212, 202, 111, 42, 255, 211>>}, key_establishment_protocol: Ockam.SecureChannel.KeyEstablishmentProtocol.XX, peer: %{plaintext_address: <<0, 17, 95, 98, 102, 49, 55, 56, 101, 54, 49, 53, 97, 52, 48, 97, 50, 50, 50>>, public_key: <<191, 154, 122, 123, 162, 162, 54, 253, 197, 240, 235, 251, 80, 45, 118, 218, 170, 169, 187, 89, 209, 189, 77, 28, 191, 199, 67, 200, 107, 239, 8, 77>>}, plaintext_address: "_fac40bcd1403d7a7", route_to_peer: ["_5c6aa3fd960f9b9e"], xx_key_establishment_state: %Ockam.SecureChannel.KeyEstablishmentProtocol.XX.Protocol{ck: 14, e: %{private: 2, public: <<86, 97, 13, 131, 172, 62, 111, 171, 246, 35, 117, 144, 80, 37, 155, 56, 142, 85, 73, 188, 165, 33, 111, 107, 221, 165, 180, 216, 20, 98, 8, 87>>}, h: <<113, 201, 179, 153, 97, 211, 2, 99, 154, 66, 106, 182, 77, 182, 153, 92, 35, 229, 237, 245, 7, 49, 49, 25, 195, 61, 212, 202, 111, 42, 255, 211>>, k: 15, m1_payload: "", m2_payload: <<0, 17, 95, 102, 97, 99, 52, 48, 98, 99, 100, 49, 52, 48, 51, 100, 55, 97, 55>>, m3_payload: "", n: 1, prologue: "", re: <<96, 132, 77, 56, 39, 238, 156, 71, 46, 231, 16, 96, 95, 14, 171, 14, 72, 222, 91, 220, 180, 81, 81, 64, 103, 136, 71, 188, 235, 161, 232, ...>>, rs: <<191, 154, 122, 123, 162, 162, 54, 253, 197, 240, 235, 251, 80, 45, 118, 218, 170, 169, 187, 89, 209, 189, 77, 28, 191, 199, 67, 200, 107, 239, ...>>, s: %{private: 1, public: <<136, 180, 218, 181, 71, 146, 21, 199, 6, 129, 243, 45, 128, 169, 61, 76, 234, 103, 14, 141, 124, 215, 155, 99, 159, 241, 150, ...>>}, vault: %Ockam.Vault.Software{id: [2, 1]}}}}
Callback mode: :handle_event_function
Postponed events: []
Last event: {:info, %{onward_route: ["_fac40bcd1403d7a7", "echo"], payload: "FOO", return_route: []}}
Queued events: []
State: {{:encrypted_transport, :ready}, %{ciphertext_address: "_74ca6b91b3a7196f", encrypted_transport: %{decrypt: {17, 0}, encrypt: {18, 0}, h: <<113, 201, 179, 153, 97, 211, 2, 99, 154, 66, 106, 182, 77, 182, 153, 92, 35, 229, 237, 245, 7, 49, 49, 25, 195, 61, 212, 202, 111, 42, 255, 211>>}, key_establishment_protocol: Ockam.SecureChannel.KeyEstablishmentProtocol.XX, peer: %{plaintext_address: <<0, 17, 95, 98, 102, 49, 55, 56, 101, 54, 49, 53, 97, 52, 48, 97, 50, 50, 50>>, public_key: <<191, 154, 122, 123, 162, 162, 54, 253, 197, 240, 235, 251, 80, 45, 118, 218, 170, 169, 187, 89, 209, 189, 77, 28, 191, 199, 67, 200, 107, 239, 8, 77>>}, plaintext_address: "_fac40bcd1403d7a7", route_to_peer: ["_5c6aa3fd960f9b9e"], xx_key_establishment_state: %Ockam.SecureChannel.KeyEstablishmentProtocol.XX.Protocol{ck: 14, e: %{private: 2, public: <<86, 97, 13, 131, 172, 62, 111, 171, 246, 35, 117, 144, 80, 37, 155, 56, 142, 85, 73, 188, 165, 33, 111, 107, 221, 165, 180, 216, 20, 98, 8, 87>>}, h: <<113, 201, 179, 153, 97, 211, 2, 99, 154, 66, 106, 182, 77, 182, 153, 92, 35, 229, 237, 245, 7, 49, 49, 25, 195, 61, 212, 202, 111, 42, 255, 211>>, k: 15, m1_payload: "", m2_payload: <<0, 17, 95, 102, 97, 99, 52, 48, 98, 99, 100, 49, 52, 48, 51, 100, 55, 97, 55>>, m3_payload: "", n: 1, prologue: "", re: <<96, 132, 77, 56, 39, 238, 156, 71, 46, 231, 16, 96, 95, 14, 171, 14, 72, 222, 91, 220, 180, 81, 81, 64, 103, 136, 71, 188, 235, 161, 232, ...>>, rs: <<191, 154, 122, 123, 162, 162, 54, 253, 197, 240, 235, 251, 80, 45, 118, 218, 170, 169, 187, 89, 209, 189, 77, 28, 191, 199, 67, 200, 107, 239, ...>>, s: %{private: 1, public: <<136, 180, 218, 181, 71, 146, 21, 199, 6, 129, 243, 45, 128, 169, 61, 76, 234, 103, 14, 141, 124, 215, 155, 99, 159, 241, 150, ...>>}, vault: %Ockam.Vault.Software{id: [2, 1]}}}}
```

Maybe the channel forwarding is not implemented yet? Because I don't see the handle_message which would handle the forwarding stage.

Maybe I'm doing it wrong, but an example of channel which forwards at least one message would be useful. 
The code I use (from repl, mostly copied from `secure_channel_test.exs`):
```
  alias Ockam.SecureChannel
  alias Ockam.Vault
  alias Ockam.Vault.Software, as: SoftwareVault
  
    secret_attributes = %{type: :curve25519, persistence: :ephemeral, length: 32}

    {:ok, responder_vault} = SoftwareVault.init()
    {:ok, responder_identity} = Vault.secret_generate(responder_vault, secret_attributes)

    {:ok, listener} =
      SecureChannel.create_listener(vault: responder_vault, identity_keypair: responder_identity)

    {:ok, initiator_vault} = SoftwareVault.init()
    {:ok, initiator_identity} = Vault.secret_generate(initiator_vault, secret_attributes)

    {:ok, channel} =
      SecureChannel.create(
        route: [listener],
        vault: initiator_vault,
        identity_keypair: initiator_identity
      )
     Ockam.Router.route(%{onward_route: [channel, "echo"], return_route: [], payload: "FOO"})
   ```

**Comment by mrinalwadhwa** [comment]
This should now work, changes merged in #1409.

Try the echo test
https://github.com/ockam-network/ockam/blob/develop/implementations/elixir/ockam/ockam/test/ockam/secure_channel_test.exs#L43-L54
