### ISSUE TITLE
rust:cargoCheck error - 'cryptoauthlib.h' file not found

### ISSUE THREAD

**Issue by mrinalwadhwa** [ockam-network/ockam#614]
I've seen this a few times over the last few days but it doesn't seem to happen consistently.

```
  //Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/target/debug/build/generate_c_bindings-8fd4e090f587098f/out/ockam_vault_atecc608a/build/ockam/vault/atecc608a/include/ockam/vault/atecc608a.h:15:10: fatal error: 'cryptoauthlib.h' file not found
  //Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/target/debug/build/generate_c_bindings-8fd4e090f587098f/out/ockam_vault_atecc608a/build/ockam/vault/atecc608a/include/ockam/vault/atecc608a.h:15:10: fatal error: 'cryptoauthlib.h' file not found, err: true
  thread 'main' panicked at 'Failed to generate bindings to Ockam Vault!: ()', c/generate_bindings/build.rs:115:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

> Task :rust:cargoCheck FAILED
```

**Comment by mrinalwadhwa** [comment]
saw this again

```
  //Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/target/debug/build/generate_c_bindings-8fd4e090f587098f/out/ockam_vault_atecc608a/build/ockam/vault/atecc608a/include/ockam/vault/atecc608a.h:15:10: fatal error: 'cryptoauthlib.h' file not found
  //Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/target/debug/build/generate_c_bindings-8fd4e090f587098f/out/ockam_vault_atecc608a/build/ockam/vault/atecc608a/include/ockam/vault/atecc608a.h:15:10: fatal error: 'cryptoauthlib.h' file not found, err: true
  thread 'main' panicked at 'Failed to generate bindings to Ockam Vault!: ()', c/generate_bindings/build.rs:115:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

> Task :rust:cargoCheck FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/build.gradle' line: 53
```

This time I ran
```
./gradlew build
./gradlew lint
```

I usually run lint first so maybe the error has something to do with that.
